### PR TITLE
Added link to Functional Design Patterns slideshare

### PR DESCRIPTION
**Pull request by digital-stoic**
I think the resource link itself is great. Maybe it would be worth to create (sub-)sections about the following patterns:
- Composition is everywhere (Composition is fractal + Types can be composed too)
- Use static types for Domain  modelling and documentation => Would be relevant to have a dedicated section about Domain Driven Design with FP (and summarize the book 'Domain Modeling Made Functional')
- Use Bind to chain tasks and error handlers

### CODE REVIEW

**Comment by JordanMartinez** [comment]
My apologies. I'd rather discuss this in an issue first before having someone open a PR (unless it's to fix a typo or something).

I think the link is helpful in some ways, but also accurate when it describes itself as "a whirlwind tour of many things". Mind opening an issue to discuss this further?

**Comment by digital-stoic** [comment]
See #288

**Comment by JordanMartinez** [comment]
Thanks

**Comment by JordanMartinez** [comment]
As stated in #288, I'm closing this since you won't be able to get to this any time soon.

**Pull request closed without merging**
