### PR TITLE
Fix typo and change phrasing

### LINKED ISSUE #514: Possible typo
https://github.com/JordanMartinez/purescript-jordans-reference/blob/d7b806061b4f67db2f59a6742f1d1e37a209345a/11-Syntax/03-Type-Level-Programming-Syntax/src/02-Basic-Syntax/10-Conventions.purs#L18
I'm not super comfortable with this stuff yet, so I'm not sure what the correct terminology would even be, but I have a strong feeling this (`value-level type`) isn't it. If it is, could you point me to the spot in the documentation that demonstrates this, thanks :)

### PR DESCRIPTION
**Pull request by ursi**
Fixes: #514

### CODE REVIEW

**Comment by JordanMartinez** [comment]
Thanks for the fix, @ursi! Similar to other PRs recently submitted, please wait until after I've merged #511 before fixing the typos. I'm moving a lot of files around and restructuring some folders to prevent nesting. I hope to have that done within another week or two.

**Comment by JordanMartinez** [comment]
@ursi Thanks for waiting. Would you mind doing this fix on top of `latestRelease` now? I did some pretty big file/folder shuffling in #511

**Comment by ursi** [comment]
good to go 👍

**Comment by JordanMartinez** [comment]
Thanks!

**Pull request merged**
