### PR TITLE
Make next major release: ps-0.13.x-v0.19.0

### LINKED ISSUE #178: Promote Foldable/Traversable folder to own folder in Hello World
I should probably link to the related paper as well...

### LINKED ISSUE #221: Switch to using ChangeLog file
[Stealing hdgarrood's comment](https://github.com/purescript/purescript/issues/3185#issuecomment-453958462), use a change log file that one has to change whenever a commit changes or breaks something. It'll be easier to track what changed in a release as a result as my current manual way is somewhat time-consuming.

### LINKED ISSUE #228: Constraint Kinds example
## Context

Section:
  Design Pattern

Issue Type:
  Bug

File:
  - Design Patterns/Simulating Constraint Kinds.md

## Body

Using PS 0.12.2 I cannot compile the example given. At the use site of the type synonym I get the error   `Unable to parse module:
  unexpected comma in constraints.`

There's also the matter of using `MyMonad` instead of `WithMyMonad`.

After some trial and error and applying compiler suggestions, I ended up with this diff that at least compiles: https://gist.github.com/linearray/239be7b3fc9cd35548f7ccc76cc79854

I also think the file needs an example for `f` or `g`, because I was unable to come up with one, but maybe that's because I mutilated the types.

### LINKED ISSUE #368: Use a single `packages.dhall` file for the entire project
This would make it easier to upgrade all package sets in the repo and provide a central place to show where I'm adding packages when needed and where their source is.

However, it's currently blocked by spacchetti/spago#349

### LINKED ISSUE #383: Update cached directories in .travis.yml file
Some are still outdated from a previous PR

### LINKED ISSUE #384: REPL Evaluation
## Context

```
Section:
  Getting Started

Issue Type:
  Bug

Folder/File(s):
  - Getting Started/The REPL.md
```

## Body

I guess

```
> :kind (Int -> Int)
Type -> Type
```

should be

```
> :kind (Int -> Int)
Type
```

### PR DESCRIPTION
**Pull request by JordanMartinez**
## Breaking

- Fixes #368
- Fixes #228 
- Fixes #178

## Changes

- Fixes #221
- Fixes #384 
- Fixes #383

### CODE REVIEW

**Comment by JordanMartinez** [comment]
CI failed due to this issue: spacchetti/spago#427

**Comment by justinwoo** [comment]
you can fix this by just removing `dist: xenial` from .travis.yml. you might have to specify bionic, but most likely not

**Comment by JordanMartinez** [comment]
Thanks for the tip!

I'm currently learning how to use neovim, so I'll finish this after
learning that better.

**Comment by JordanMartinez** [comment]
@justinwoo So, I tried removing `dist` and downgrading to `bionic` and the issue still arose. Thanks for the tip though!

**Pull request merged**
