### PR TITLE
Convert to `mdbook` website

### PR DESCRIPTION
**Pull request by JordanMartinez**
This PR is a work in progress. Below is a summary of the changes so far.

1. To better separate their content from one another, the `Projects` folder's structure was made to look more like the `Syntax` folder's structure. The top-level folder now houses each part as its own folder. In other words `01-Library Guides` and `11-Random-Number-Game` and `12-ToC-Generator` are all subfolders within `22-Projects`. In the process of making this update, a few files were likely lost (e.g. `Free`-based implementation of the random number game). I'm not bothered by that because I feel like some of these examples are more confusing than they are helpful. In other places, I feel like the code I wrote previously is more complicated than it needs to be.
1. Due to the changes above, running `for-each-folder--install-deps-and-compile.sh` won't remove all of the old files in `22-Projects`.
1. `mdbook` makes a few assumptions that do not work well with this project. As a result, I've duplicated the `ToC-Generator` folder and adjusted it to output the necessary ToC file I would need the `SUMMARY.md` file to contain. I'm still working on this tool

The work that has yet to be done:
- [x] A folder with a `Readme.md` file should be rendered as the folder name while displaying the readme's content. Right now, the folder is displayed as a placeholder link that enforces structure and the `Readme.md` file is displayed as the first item below it.
- [x] A PureScript or JavaScript file needs to have a new Markdown file created that stores its content within a code block via a `{{#include path/to/file-name.purs}}` handlebar. 
- [x] The output name of a page should remove the file extension unless it's a PureScript or JavaScript file.

Other work that requires more thought:
- By rendering a folder name without a link, we enforce structure in the ToC. However, that entry in the ToC in the sidebar is then grayed out. `mdbook` assumes this link is still a work-in-progress. I haven't found any other way to enforce such structure. So, in addition to this work, once `mdbook build` returns, I also need to update the outputted `variables.css` file's `--sidebar-non-existent` color variable to be some other scheme. I might be able to do this by adding my own custom css, but I haven't explored this further.
- Once I've finished fixing everything above, I need to figure out where I will host the resulting website. I could do it in this repo, but I fear that it might bloat the repo with additional files that I would prefer not be there in the first place.

## Seeing the website right now

If you want to generate this website yourself, run the following commands:
```bash
git clone https://github.com/JordanMartinez/purescript-jordans-reference.git
cd purescript-jordans-reference
git checkout origin/convertToMdBook
cd 22-Projects/13-Mdbook-ToC
spago bundle-app --main ToC.ReaderT.Main --to dist/mdbook-toc.js
cd ../../
node 22-Projects/13-Mdbook-ToC/dist/mdbook-toc.js -r "." -o "./SUMMARY.md" -s "./mdbook/Summary-header.md" -p "../.."
mdbook serve -o
```

### CODE REVIEW

**Comment by milesfrain** [comment]
You can replace the last commands:
```
mdbook build
firefox book/index.html
```
with:
```
mdbook serve -o
```
to get a live-updating version (with auto-refresh for saved changes).

**Comment by JordanMartinez** [comment]
Thanks for the tip!

**Comment by JordanMartinez** [comment]
> A PureScript or JavaScript file needs to have a new Markdown file created that stores its content within a code block via a {{#include path/to/file-name.purs}} handlebar.

The current problem with this is that `PureScript` isn't included in the list of languages for `highlight.js` used by `mdbook`. Closest thing I can get with the least amount of effort is using `haskell` instead.

**Comment by milesfrain** [comment]
Here's a workaround for that:
https://github.com/purescript-halogen/purescript-halogen/pull/664#issuecomment-637679500

https://github.com/purescript-halogen/purescript-halogen/pull/664/commits/f4a4de8fd7a3db1ca3b08f3d6f4c4a8d64d700cb#diff-412cf5cd6f41f760ef5cde36dbc40111

**Comment by JordanMartinez** [comment]
Thanks for the context, Miles. That's good to know.

**Comment by JordanMartinez** [comment]
Code files (e.g. JavaScript and PureScript files) are now generated in `./mdbook/code` as a markdown file that hacks `mdbook`'s `{{#include file-path}}` to insert the content into the markdown file.

Instructions above have been updated. Example of output:
example-screenshot-of-syntax-highlighting

**Pull request merged**
