### PR TITLE
Remove extra backticks

### PR DESCRIPTION
**Pull request by ursi**

### CODE REVIEW

**Comment by JordanMartinez** [comment]
@ursi Sorry for the late response. Thanks for the PR. However, the `ps-0.14-syntax' branch is the branch into which this fix should go, and it's possible I've already fixed this there.

**Comment by ursi** [comment]
It's not fixed there either. But this patch doesn't merge cleanly with that branch. I will get around to making a new one at some point if you don' beat me to it.

**Comment by JordanMartinez** [comment]
Ok, thanks!

**Comment by ursi** [comment]
done in #486

**Pull request closed without merging**
